### PR TITLE
fix: Adds operatorSend, operatorBurn, approve, safeTransferFrom

### PR DESCRIPTION
**Pull request by andyogaga**
https://app.clickup.com/t/866abevnp

### CODE REVIEW

**Comment by frozeman** [comment]
Task linked: [CU-866abevnp Adds generic tx to test dApp](https://app.clickup.com/t/866abevnp)

**Review by richtera — APPROVED** [review]
That reminds me we have to disable the GitHub pages stuff

**Review by dzbo — APPROVED** [review]
lgtm, btw we still have `'numberToHex' is defined but never used` around, can you fix it?

**Comment by andyogaga** [comment]
> lgtm, btw we still have `'numberToHex' is defined but never used` around, can you fix it?

Sorry, merged it before seeing this comment. Fixing it in my next PR

**Pull request merged**
